### ISSUE TITLE
watch loop

### ISSUE THREAD

**Issue by sinedied** [thales-poles-ra/starter-kit#1]
Sometimes a file modification triggers an infinite loop in the watch task.

**Comment by davisp1** [comment]
Surely because of changes on index.html during inject, i try to solve it 6cf6958c4811c2d4fba63a8a87e295a3edae5d73

**Comment by sinedied** [comment]
Resolved with this [pull request](https://github.com/thales-poles-ra/starter-kit/pull/3).

Next time, don't forget to specify the issue # in the commit message, like "fixed issue #1" to link it automatically to the issue.
